export enum FileExtensions {
  DIR = 'dir',
  PDF = 'pdf',
  JPG = 'jpg',
  JPEG = 'jpeg',
  GIF = 'gif',
  PNG = 'png',
  MOV = 'mov',
  AVI = 'avi',
  XLS = 'xls',
  DOC = 'doc',
  DOCX = 'docx',
  TXT = 'txt',
  ZIP = 'zip',
  RAR = 'rar',
  CSS = 'css',
  HTML = 'html',
  SVG = 'svg',
  PSD = 'psd',
  PPT = 'ppt',
  MP3 = 'mp3',
  MP4 = 'mp4',
  EXE = 'exe',
  XML = 'xml',
  SYS = 'sys',
}
